In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.13.0+cpu


## Introduction to tensors



### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [3]:
# scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[2,3],
                       [5,6]])

MATRIX

tensor([[2, 3],
        [5, 6]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]


tensor([5, 6])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [5,6,7],
                        [10,11,12]]])

TENSOR


tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0,1,2]

tensor(7)

### Random tensors

Why random tensors?

Random tensors are importanat because the way many neural networks learn is that they start with tensors full of random numbers and then ajdust those random numbers to better represent the data.

``Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [17]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1875, 0.9752, 0.7974, 0.9760],
        [0.5074, 0.0259, 0.8346, 0.7830],
        [0.2681, 0.4605, 0.4989, 0.8262]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
# Creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width , color channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [21]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [25]:
# use torch.arange() works better than torch.range() for some reason
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

NOTE : Tensor datatypes is one of the 3 main errors most run with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [27]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, 
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype=torch.int32)

### Getting information from tensors attributes
1. Tensors not right datatype - to get datatype from tensor , can use tensor.dtype
2. Tensors not right shape - use tensor.shape
3. Tensors not on the right device - use tensor.device

In [32]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4880, 0.6189, 0.9240, 0.7120],
        [0.6620, 0.0177, 0.4578, 0.5991],
        [0.0663, 0.5343, 0.9967, 0.5668]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.4880, 0.6189, 0.9240, 0.7120],
        [0.6620, 0.0177, 0.4578, 0.5991],
        [0.0663, 0.5343, 0.9967, 0.5668]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensors operations)

Tensor operation include :
 * Addition
 * Subtraction
 * Multiplication (element-wise) and Division
 * Matrix Multiplication
 

In [34]:
# Create a tensor and add something to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [36]:
# subtraction
tensor - 1

tensor([0, 1, 2])

In [37]:
# PyTorch inbuilt functions
torch.mul(tensor,10) , torch.add(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise Matrix Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match
2. The resulting matric has the shape of the **outer dimentions**


In [38]:
# Element-wise multiplication
print(tensor ,"*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [39]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [40]:
# Matrix Multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)


### One of the most common erroros in deep learning : shape errors


In [41]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.matmul(tensor_A , tensor_B)
torch.mm(tensor_A , tensor_B) # torch.mm is the same as torch.matmul (it;s an alias for matmul)

# it doesn;t work cus the shapes for both matrix is (3,2) for both , this shape can;e be multiplied 


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issue , we can manipulate the shape of one of our tensor using a **transpose**

In [52]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [53]:
tensor_B.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
# The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A , tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [55]:
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.T.shape} ")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimentions must match")
print("Output: \n")
output = torch.mm( tensor_A , tensor_B.T)
print(output)
print(f"\n Output Shape : {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([2, 3]) 
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimentions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output Shape : torch.Size([3, 3])


### Finding the min , max , mean , sun , etc (Tensor aggregation)


In [56]:
# create a tensor

x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [58]:
# find the max 
torch.max(x) , x.max()


(tensor(90), tensor(90))

In [59]:
# find the mean
torch.mean(x)

# this doesn;t work cus for mean , the datatype must be either float or complex datatype but the datatype we have is int64 as we checked before so we can use float32 to make it work , heh



RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [61]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
#find the position in tensor that has the minimum value with argmin() -> returns index value of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(0)

In [66]:
# find the positoin in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

### Reshaping , Stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an impot tensor of a certain shape but keep the same memory
* Stacking - combining multiple tensors on top of each other (vstack) , or side by side (hstack).
* Squeeze - removes all `1` dimentions from a tensor
* unsqueexe - add a `1` dimention to a target tensor
* permute - return a view of the input with dimentions permutted (swapped) in a certain way




In [67]:
# creating a tensor

import torch
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [68]:
# Add an extra dimensions
x_reshaped = x.reshape(1 , 10)
x_reshaped , x_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [69]:
x_reshaped = x.reshape(10 , 1)
x_reshaped , x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [70]:
x_reshaped = x.reshape(5 , 2)
x_reshaped , x_reshaped.shape

# and so on , as long as the reshape is compatible with the original shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [71]:
# Change the view
z = x.view( 1 , 10 )
z , z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [72]:
#changing z changed x [because a view of a tensor shares the same memory as the original]

z[ : , 0] = 5
z , x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [73]:
# stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x] , dim=0)
x_stacked , x_stacked.shape

# vstack is dim = 0 and hstack is dim = 1


(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [74]:
x = torch.zeros( 2 , 1 , 2 , 1 , 2 )
x.size()

torch.Size([2, 1, 2, 1, 2])

In [75]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [76]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [77]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [78]:
x_reshaped , x_reshaped.shape

(tensor([[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [79]:
x_reshaped.squeeze()

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [80]:
x = torch.arange(1.,10.)
x_reshaped = x.reshape(1 , 9)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [81]:
#torch.unsqueeze() - adds a single dimention to a target tensor at a specific dim (dimention)

print(f"Previous targer :  {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

#Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous targer :  tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [82]:
# torch.permute - rearranges  the dimentions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3)) #height , width , color channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute( 2 , 0 , 1 ) #shifts axis 0->1 , 1->2 and 2->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted}")

Previous shape : torch.Size([224, 224, 3])
New shape : tensor([[[0.6790, 0.0786, 0.8883,  ..., 0.3740, 0.2943, 0.8391],
         [0.0169, 0.8142, 0.9733,  ..., 0.0094, 0.2787, 0.2853],
         [0.9737, 0.8718, 0.8149,  ..., 0.6143, 0.9070, 0.2106],
         ...,
         [0.4270, 0.6165, 0.7898,  ..., 0.9961, 0.7416, 0.9307],
         [0.0210, 0.9878, 0.1068,  ..., 0.9227, 0.1581, 0.7067],
         [0.6835, 0.9695, 0.4075,  ..., 0.9266, 0.7355, 0.6237]],

        [[0.3699, 0.6994, 0.6419,  ..., 0.4733, 0.7652, 0.1368],
         [0.3966, 0.7099, 0.7364,  ..., 0.6286, 0.3478, 0.0755],
         [0.2337, 0.1180, 0.5673,  ..., 0.5140, 0.3678, 0.2309],
         ...,
         [0.9046, 0.5989, 0.8473,  ..., 0.7784, 0.4095, 0.9377],
         [0.6368, 0.5442, 0.9600,  ..., 0.3771, 0.3945, 0.3045],
         [0.8160, 0.5797, 0.7018,  ..., 0.4138, 0.2507, 0.9794]],

        [[0.9222, 0.2094, 0.1205,  ..., 0.4690, 0.8453, 0.1719],
         [0.1506, 0.3831, 0.5298,  ..., 0.7213, 0.8029, 0.7303],
   

In [83]:
x_original[0,0,0] = 67
x_original , x_permuted

(tensor([[[6.7000e+01, 3.6990e-01, 9.2220e-01],
          [7.8553e-02, 6.9943e-01, 2.0936e-01],
          [8.8831e-01, 6.4193e-01, 1.2053e-01],
          ...,
          [3.7396e-01, 4.7334e-01, 4.6896e-01],
          [2.9428e-01, 7.6519e-01, 8.4526e-01],
          [8.3910e-01, 1.3677e-01, 1.7188e-01]],
 
         [[1.6902e-02, 3.9664e-01, 1.5056e-01],
          [8.1415e-01, 7.0993e-01, 3.8305e-01],
          [9.7329e-01, 7.3636e-01, 5.2976e-01],
          ...,
          [9.4243e-03, 6.2862e-01, 7.2129e-01],
          [2.7865e-01, 3.4780e-01, 8.0285e-01],
          [2.8527e-01, 7.5480e-02, 7.3032e-01]],
 
         [[9.7367e-01, 2.3373e-01, 3.8829e-01],
          [8.7184e-01, 1.1799e-01, 3.6511e-01],
          [8.1485e-01, 5.6726e-01, 5.7276e-01],
          ...,
          [6.1427e-01, 5.1397e-01, 5.3487e-01],
          [9.0696e-01, 3.6780e-01, 3.5900e-01],
          [2.1062e-01, 2.3092e-01, 3.1967e-01]],
 
         ...,
 
         [[4.2697e-01, 9.0455e-01, 1.9326e-02],
          [6.1645e

### Indexing (selecting data from tensors)
indexing with PyTorch is similar to indexing with NumPy

In [85]:
# Create a tensor
import torch 
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [86]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
# index on the middle bracket (dim=1)
x[0][0] ,x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [90]:
# Let;s indx on the most inner bracker (last dimention)
x[0][0][0]

tensor(1)

In [93]:
x[0,1,1]

tensor(5)

In [94]:
# use ":" to select all of a target dimention
x[:,0]

tensor([[1, 2, 3]])

In [95]:
# get all value of 0th and 1th dimention but only 1 of 2nd dimention
x[:,:,1]

tensor([[2, 5, 8]])

In [96]:
# get all value of the 0 dimention but ony the 1 indec of 1st and end dimention
x[:,1,1]

tensor([5])

In [98]:
#get index 0 of 0th dimention and all values of 2nd dimention
x[0,0,:]

tensor([1, 2, 3])

In [102]:
x[0,2,2]

tensor(9)

In [103]:
x[:,:,2]

tensor([[3, 6, 9]])