In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.13.0+cpu


## Introduction to tensors



### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [4]:
# scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[2,3],
                       [5,6]])

MATRIX

tensor([[2, 3],
        [5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]


tensor([5, 6])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [5,6,7],
                        [10,11,12]]])

TENSOR


tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0,1,2]

tensor(7)

### Random tensors

Why random tensors?

Random tensors are importanat because the way many neural networks learn is that they start with tensors full of random numbers and then ajdust those random numbers to better represent the data.

``Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0967, 0.5424, 0.2136, 0.2550],
        [0.9787, 0.5167, 0.0553, 0.6511],
        [0.7807, 0.7965, 0.0871, 0.3348]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width , color channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [22]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [26]:
# use torch.arange() works better than torch.range() for some reason
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

NOTE : Tensor datatypes is one of the 3 main errors most run with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [28]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, 
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype=torch.int32)

### Getting information from tensors attributes
1. Tensors not right datatype - to get datatype from tensor , can use tensor.dtype
2. Tensors not right shape - use tensor.shape
3. Tensors not on the right device - use tensor.device

In [33]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2351, 0.4856, 0.0421, 0.4400],
        [0.5003, 0.1878, 0.1617, 0.6189],
        [0.9124, 0.5372, 0.2214, 0.8520]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.2351, 0.4856, 0.0421, 0.4400],
        [0.5003, 0.1878, 0.1617, 0.6189],
        [0.9124, 0.5372, 0.2214, 0.8520]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensors operations)

Tensor operation include :
 * Addition
 * Subtraction
 * Multiplication (element-wise) and Division
 * Matrix Multiplication
 

In [35]:
# Create a tensor and add something to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [37]:
# subtraction
tensor - 1

tensor([0, 1, 2])

In [38]:
# PyTorch inbuilt functions
torch.mul(tensor,10) , torch.add(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise Matrix Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match
2. The resulting matric has the shape of the **outer dimentions**


In [39]:
# Element-wise multiplication
print(tensor ,"*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [40]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [41]:
# Matrix Multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)


### One of the most common erroros in deep learning : shape errors


In [42]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.matmul(tensor_A , tensor_B)
torch.mm(tensor_A , tensor_B) # torch.mm is the same as torch.matmul (it;s an alias for matmul)

# it doesn;t work cus the shapes for both matrix is (3,2) for both , this shape can;e be multiplied 


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issue , we can manipulate the shape of one of our tensor using a **transpose**

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T


tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A , tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [43]:
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.T.shape} ")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimentions must match")
print("Output: \n")
output = torch.mm( tensor_A , tensor_B.T)
print(output)
print(f"\n Output Shape : {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([2, 3]) 
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimentions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output Shape : torch.Size([3, 3])


### Finding the min , max , mean , sun , etc (Tensor aggregation)


In [48]:
# create a tensor

x = torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
# find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [47]:
# find the max 
torch.max(x) , x.max()


(tensor(90), tensor(90))

In [ ]:
# find the mean
torch.mean(x)

# this doesn;t work cus for mean , the datatype must be either float or complex datatype but the datatype we have is int64 as we checked before so we can use float32 to make it work , heh



RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [51]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))